RDD-493: Build and deploy a non-functional Study Management API that requires authentication from AWS Cognito
PA-NIHR-CRN/nihr-study-management pull request #1
Opened 2024-01-26 15:39 UTC by pgadzios

Initial commit of the Study Management API which includes a HomeController with no functionality aside from two HTTP GET methods, one that requires authentication and one does not.

Further functionality will follow in subsequent user stories.

2024-01-26 16:21 UTC, Jaffacakes82 commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Dockerfile
@con-nihr are we using containerised applications for our Lambdas on VS?

2024-01-26 16:22 UTC, Jaffacakes82 commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/NIHR.StudyManagement.Api.csproj
@pgadzios it's a remarkably pedantry comment, and more to appease my OCD, but as API is an acronym, could we capitalise?

2024-01-26 16:23 UTC, Jaffacakes82 commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/serverless.template
What's this file used for?

2024-01-29 10:01 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/NIHR.StudyManagement.Api.csproj
Sure, I'll do that now. It was mostly to follow existing Microsoft classes like "ApiController" or "ApiExplorerSettings"

2024-01-29 10:05 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/serverless.template
This file is provided as part of the Visual Studio AWS Lambda template for an ASP NET Core project. I left it in and have modified appropriately it as I believe it's very useful during development. With it, an authenticated user in Visual Studio (i.e. with valid AWS Credentials) can simply right-click on the project and deploy the entire application to AWS using Cloudformation (additional settings held in aws-lambda-tools-defaults.json). Essentially it's infrastructure code for the lambda and API gateway.

I've given the names in the file appropriate for sandbox components, so they won't interfere with anything deployed automatically using terraform with DEV naming convention.

Let me know if you'd prefer the file to be removed.

2024-01-29 10:07 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Dockerfile
Just additional info, the only reason I used a container was because as far as I'm aware, .NET 7 runtime is only available to AWS Lambda in containers, and not native runtime. I know we talked about using the latest .NET available, which is 8 but as it's quite new and I think quite a bit more fiddly to use for a lambda, I decided to stick with .NET 7 for now.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

2024-01-29 11:43 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/NIHR.StudyManagement.Api.csproj
Names of "Api" have now been renamed to "API".
Please let me know if this is OK or I've missed anything.

2024-01-29 12:40 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/NIHR.StudyManagement.Api.csproj
@Jaffacakes82 
Under .Net default conventions, acronyms of more than two letters use PascalCase.

My vote would be to stick with the default rules, though we can override this if we want.
I believe the reason for this is that mixed case aids visually scanning the line quickly, especially when multiple acronyms run together.
e.g.
HTMLToPDFAPIJWTGenerator -> HtmlToPdfApiJwtGenerator

https://learn.microsoft.com/en-us/visualstudio/code-quality/ca1709?view=vs-2022#rule-description

_By convention, two-letter acronyms use all uppercase letters, and acronyms of three or more characters use Pascal casing. The following examples use this naming convention: 'DB', 'CR', 'Cpa', and 'Ecma'. The following examples violate the convention: 'Io', 'XML', and 'DoD', and for non-parameter names, 'xp' and 'cpl'.

'ID' is special-cased to cause a violation of this rule. 'Id' is not an acronym but is an abbreviation for 'identification'._

2024-01-30 17:14 UTC, con-nihr requested changes

2024-01-30 17:14 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +            if(studyManagementAPIConfiguration.JwtTokenValidationConfiguration.OverrideJwtTokenValidation)
`&& !env.IsProduction()`
Ideally log an error if this is configured in production.
If that is the case the bypass should have no effect and the production application should operate correctly.

2024-01-30 17:14 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/appsettings.Development.json
> +  "StudyManagementAPIConfiguration": {
We are already in the context of a 'configuration' file so I think we can drop the suffix.

- `StudyManagementApi`
    - `JwtTokenValidation`
        - `OverrideClaims`
        - etc

2024-01-31 15:21 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +                ValidateAudience = false
To be honest as this feature didn't have much functionality, I elected to not introduce infrastructure and domain projects as part of this work. My intention is to change this to be a bit more elegant reading a secret name from AWS lambda environment variable, then retrieving the secret value via secrets manager for sensitive values.
Would that be OK?

2024-01-31 16:19 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/NIHR.StudyManagement.Api.csproj
I tend to agree with the convention above. @Jaffacakes82 are you comfortable then for me to revert back to "Api"?

2024-02-01 11:25 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +                ValidateAudience = false
@con-nihr I can modify the code to read from AWS secret manager for the issuer key, but would you like logic as well that will conditionally read the value from local app settings during local development?

2024-02-01 11:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Dockerfile
I am keen to use the latest .Net runtime too.
.Net 8.0 support is planned for "February 2024", so by the time this is ready to deploy we should be on the latest.

https://github.com/aws/aws-lambda-dotnet/issues/1611

2024-02-01 11:52 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +                ValidateAudience = false
If we read the key from configuration and use the AWS secrets manager configuration provider we can transparently support local app settings vs aws config.

Happy to revisit this when we need it.

2024-02-01 15:12 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +        var studyManagementAPIConfigurationSection = Configuration.GetSection("StudyManagementAPIConfiguration");
@con-nihr  the main reason I've read configuration and then registered on separate lines is so that I can use the config/settings in the same method. If I register in a single line with Configure or AddOptions then won't I have to build the service provider in order to then retrieve the settings so that I can know whether or not to override the Jwt events? that felt a bit overkill to me.

2024-02-02 13:32 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +        .AddJwtBearer(options =>
Any pros / cons to simply removing `JwtBearer` auth if `JwtBearerOverride` is configured in non-prod?

2024-02-02 13:57 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Dockerfile
Docker has now been removed and project downgraded to .NET 6.

2024-02-02 13:58 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +                ValidateAudience = false
Have refactored the application settings a little. No secrets manager implementation yet as currently we don't need it. The only required configuration value we need is the audience/issuer and this is retrieved from the OIDC ./well-known configuration endpoint thus is not sensitive/secret. It's simply an environment variable that will be set via terraform.

2024-02-02 14:17 UTC, con-nihr approved these changes

2024-02-05 09:35 UTC, merged