Bugfix/rdd 494 add password secret manager
PA-NIHR-CRN/nihr-study-management pull request #6
Opened 2024-02-28 15:37 UTC by pgadzios

The initial intention was to use IAM policies to access the MySql instance, however this didn't work as intended and it has been decided to, in the short term for the PoC, use a connection string with conventional username/password authentication.

Therefore we need to add a new bit of code to retrieve the password from AWS secrets.

2024-02-28 15:38 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/serverless.template
Updated the routes in this template which is used for pushing up the lambda/API to SANDBOX via CloudFormation during local development work.

2024-03-05 09:37 UTC, pgadzios commented
Hi @con-nihr are you able to please cast your eye over this PR when you have an opportunity.

2024-03-06 09:49 UTC, con-nihr requested changes
Let's discuss use of some common code for merging configuration from secrets manager.

2024-03-06 09:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Configuration/AwsSecretsManagerClient.cs
This is a common pattern we are employing across the applications, I would like to reuse a single approach to reading secrets via a ConfigurationProvider.
@Jaffacakes82 FYI

2024-03-06 09:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +            if (!string.IsNullOrEmpty(studyManagementApiSettings.Data.PasswordSecretName))
It is acceptable to put the full connection string in secrets manager.

2024-03-06 09:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Configuration/DatabaseSettings.cs
> +        public string PasswordSecretName { get; set; } = "";
ConnectionString only is fine.

2024-03-06 09:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/Startup.cs
> +    private string GetAwsSecretPassword(string secretName)
Use a ConfigurationProvider rather than reading this directly.

2024-03-06 09:49 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Api/appsettings.Development.json
> +      "PasswordSecretName": "<optional password secret name. If empty, password expected in connection string.>"
Put full connection string in Secrets Manager if it is sensitive.

2024-03-06 14:23 UTC, merged