Adding implementation to publish the data of a study to Kafka or S3 after it's been registered
PA-NIHR-CRN/nihr-study-management pull request #7
Opened 2024-03-01 08:39 UTC by pgadzios

The Kafka implementation is the desired approach, however given there are some challenges on the Data Platform infrastructure side of things, an S3 implementation has been added to support the DP integration more quickly for PoC.

2024-03-05 09:38 UTC, pgadzios commented
Hi @con-nihr are you able to please cast your eye over this PR when you have an opportunity.

2024-03-06 10:01 UTC, con-nihr requested changes
Agreed, we need to making some reusable NSIP abstractions. That's a job for later.

2024-03-06 10:01 UTC, con-nihr commented on NIHR.StudyManagement/NIHR.StudyManagement.Domain/Services/GovernmentResearchIdentifierService.cs
> +            await _messagePublisher.PublishAsync("gris-study-registered", _settings.DefaultLocalSystemName, researchStudy, cancellationToken);
Can you pull out the event type strings into a central 'registry' of `consts`?

2024-03-06 14:42 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Infrastructure/MessageBus/StudyManagementKafkaMessageProducer.cs
> +                catch (Exception ex)
Yep, classic example of copy-paste :) from this file https://github.com/PA-NIHR-CRN/nihr-nsip/blob/main/NIHR.NSIP/NIHR.NSIP.KafkaSdk/KafkaProducer.cs

This try/catch has now been removed.

2024-03-06 14:43 UTC, pgadzios commented on NIHR.StudyManagement/NIHR.StudyManagement.Domain/Services/GovernmentResearchIdentifierService.cs
> +            await _messagePublisher.PublishAsync("gris-study-registered", _settings.DefaultLocalSystemName, researchStudy, cancellationToken);
Magic string removed into constant GrisNsipEventTypes

2024-03-11 11:03 UTC, merged